[build]
builder = "nixpacks"

[deploy]
startCommand = "python run_automated_system.py --mcp-only"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NIXPACKS_PYTHON_VERSION = "3.11"
