[build]
builder = "nixpacks"

[deploy]
startCommand = "python final_mcp_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_INSTALL_CMD = "pip install -r requirements-railway.txt"
